# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 868d7f144effdb83cff925663d8ba5103b0658ef33a04db2ae27a8998eb84c23e61cbcea54e0d12048c2eb93daa1e26948adb4b40dafc58c59bbd3275ab962df

test:
  secret_key_base: 8260670b9564359071f90410d92938b4848889056afac3312db7c807986e86cec46683949a81982dd28955cdf7c505a0e1e9122a0fd795159b749e8042973b57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
